# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation in the "docs/" directory with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as HTML
formats:
  - htmlzip

# Declare the Python requirements required to build your documentation
python:
  install:
    - requirements: requirements.txt
