# MkDocs configuration

# Required
site_name: 'Python UrBackup'
site_description: 'A Python wrapper to access and control an UrBackup server'
site_author: 'Judah Paul'
repo_name: 'judahpaul16/python-urbackup'
repo_url: 'https://github.com/judahpaul16/python-urbackup'
docs_dir: 'docs'
site_dir: 'site'

# Theme configuration
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  features:
    - tabs
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'https://www.urbackup.org/favicon.ico'
  favicon: 'https://www.urbackup.org/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - git-revision-date-localized

# Extra configuration
extra:
  social:
    - type: 'github'
      link: 'https://github.com/judahpaul16/python-urbackup'
